<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<style>
div
	{
        height:50%;
        width:50%;
        border-color:black;
        background-color:aliceblue;
        margin:auto;
        
        border-style:solid;
	}
	font
	{
	size:5;
	}
</style>
<body bgcolor="#0a2f5b">
<br>
<font color="white" size="6"><center>Your pickup request is created successfully</center></font><br/>
<br/>


<%
String name=request.getParameter("hd");
int price=Integer.parseInt(request.getParameter("pri"));
int quantity=Integer.parseInt(request.getParameter("qty"));

String s_name=request.getParameter("s_name");
String opt=request.getParameter("opt");
out.println("<div><br>");
out.println("<center><b>");
out.println("<center><font color=blue size=3>Your parcel_id is:"+101+"</font><br></center>");
out.println("<div><br>");
out.println("<br>");
out.println("Price is: "+price+"<br>");
out.println("Quantity is: "+quantity+"<br>");
int total=(price*quantity)-100;

out.println("Your Bill is generated by name:"+s_name+"<br/>");
out.println("Your Total amount or Bill is:"+total+"</font><br/><br/>");

out.println("</b></center>");
out.println("<br></div>");

%>
<br><br>
<form action="index.jsp">
<center><input type="submit" value="Click to get QR-Code"/></center>
<br>
</form>
</body>
</html>